BEGIN;

CREATE TABLE IF NOT EXISTS clientes (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula VARCHAR(20) NOT NULL UNIQUE,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    fecha_nacimiento DATE,
    direccion VARCHAR(200),
    telefono VARCHAR(20),
    correo VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR(50) NOT NULL UNIQUE,
    contraseña VARCHAR(255) NOT NULL,
    rol VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS cuentas (
    id_cuenta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL REFERENCES clientes(id_cliente) ON DELETE CASCADE,
    numero_cuenta VARCHAR(30) NOT NULL UNIQUE,
    tipo_cuenta VARCHAR(30) NOT NULL,
    fecha_apertura DATE NOT NULL DEFAULT CURRENT_DATE,
    saldo NUMERIC(15, 2) NOT NULL DEFAULT 0 CHECK (saldo >= 0),
    estado VARCHAR(20) NOT NULL DEFAULT 'Activa'
        CHECK (estado IN ('Activa', 'Inactiva', 'Suspendida', 'Cerrada'))
);

CREATE TABLE IF NOT EXISTS transacciones (
    id_transaccion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cuenta BIGINT NOT NULL REFERENCES cuentas(id_cuenta),
    tipo VARCHAR(40) NOT NULL CHECK (
        tipo IN (
            'Deposito',
            'Depósito',
            'Retiro',
            'Transferencia Enviada',
            'Transferencia Recibida',
            'Desembolso Préstamo'
        )
    ),
    monto NUMERIC(15, 2) NOT NULL CHECK (monto > 0),
    fecha TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prestamos (
    id_prestamo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL REFERENCES clientes(id_cliente),
    monto NUMERIC(15, 2) NOT NULL CHECK (monto > 0),
    interes NUMERIC(7, 2) NOT NULL CHECK (interes >= 0),
    plazo INTEGER NOT NULL CHECK (plazo > 0),
    estado VARCHAR(20) NOT NULL DEFAULT 'Pendiente'
        CHECK (estado IN ('Pendiente', 'Aprobado', 'Rechazado'))
);

CREATE INDEX IF NOT EXISTS idx_banco3_cuentas_cliente ON cuentas(id_cliente);
CREATE INDEX IF NOT EXISTS idx_banco3_transacciones_cuenta_fecha
    ON transacciones(id_cuenta, fecha DESC, id_transaccion DESC);
CREATE INDEX IF NOT EXISTS idx_banco3_prestamos_cliente ON prestamos(id_cliente);

COMMIT;
